### PR TITLE
Fix date and expiry issues

### LINKED ISSUE #155: [PE-D] Bug in expiring command
Even though those food items have already expired, it shows it is expiring in the next week.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: hussain1998/ped#3

### LINKED ISSUE #169: [PE-D] Functionality Bugs
I put expired date 16-03-1999, but the error message showed expiring in the next week. It should be a problem because it already expired. Maybe it would be better to spend some time to deal with it or at least differ the expiring one and expired one! 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Cocokkkk/ped#7

### LINKED ISSUE #180: [PE-D] Expiring incorrect information
The food is `expired` but the information suggests that the food is `expiring`.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: tzexern/ped#6

### LINKED ISSUE #183: [PE-D] Incorrect Information for invalid date
`'dd-mm-yy'` should be `'dd-mm-yyyy'`?

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: tzexern/ped#9

### LINKED ISSUE #192: [PE-D] Suggestion #2 - food items that have already expired
Here, even though all the items in the frigde have expired, it seems to come under the list of "expiring within a week" which is not the best way to optimize the application's purpose. A suggestion is to include a command that lets you detect all the expired items so that you know which to discard.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: vaiish371/ped#4

### PR DESCRIPTION
**Pull request by Vinci-Hu**
@Vinci-Hu
Add check expiry at AddCommand & add expired display at ExpiringCommand
@Vinci-Hu
Fix tests to comply, add expiring test

### CODE REVIEW

File: src/main/java/seedu/fridgefriend/command/AddCommand.java [hunk 1]
```diff
@@ -56,8 +56,8 @@ public void execute() throws RepetitiveFoodIdentifierException {
 
     private void addFood() throws RepetitiveFoodIdentifierException {
         assert foodToAdd != null : "Unable to add a null food";
-        Storage.saveHistoryData(foodToAdd);
         fridge.add(foodToAdd);
+        Storage.saveHistoryData(foodToAdd);
```
Comment (Leeyp) [inline src/main/java/seedu/fridgefriend/command/AddCommand.java:60]: Shifting the order of the foodToAdd would result in the history log data adding the post-edited quantity instead of the original quantity. Has this been addressed?

**Review by Leeyp — COMMENTED** [review]
Clarification regarding the edit of the History command


As long as the rest of the expiry command works, it is good!

**Review by Leeyp — APPROVED** [review]
Clarified offline, looks good to me.

**Review by SimJJ96 — APPROVED** [review]
LGTM
