### PR TITLE
Fixed Storage improper validation

### LINKED ISSUE #188: [PE-D] File delimiter for save file `fridgeData`
including the file delimit `,` in the `FOODNAME`

would cause some information error when loading up the save file as shown in the screenshot.

Maybe it's good to mention under the UG on something about the saving and loading of data.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: tzexern/ped#14

### LINKED ISSUE #200: [PE-D] Invalid naming of food by including ":" or ","
The program allows users to add food whose names contain ":" or ",". But when you close and reentering the program, that data would be invalid. Perhaps an instruction can be added to tell users not to use them, or the team can check for the usage of these characters when adding.

Step 1: Enter "add pear, juice /cat beverage /exp 30-06-2021 /loc lower_shelf /qty 5"
Step 2: Enter "add coconut: juice /cat beverage /exp 30-06-2021 /loc lower_shelf /qty 5"
Step 3: Enter "bye" to exit program.
Step 4: Run the program again.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: 8kdesign/ped#6

### PR DESCRIPTION
**Pull request by Leeyp**
Closes #188 #200

### CODE REVIEW

**Review by Vinci-Hu — APPROVED** [review]
LGTM. Looks brutal but effective.

File: src/main/java/seedu/fridgefriend/utilities/Storage.java [hunk 1]
```diff
@@ -115,20 +116,45 @@ private static void readFridgeData() throws FileNotFoundException, InvalidDateEx
...
+    }
+
+    private static String loadFoodNameFromLine(String line, String startIndex, String endIndex) {
+        return line.substring(line.indexOf(startIndex) + startIndex.length(), line.lastIndexOf((endIndex)));
+    }
+
+    private static String loadFoodDataFromLine(String line, String startIndex, String endIndex) {
+        return line.substring(line.lastIndexOf(startIndex) + startIndex.length(), line.lastIndexOf((endIndex)));
+    }
+    //@@author
```
Comment (kwokyto) [inline src/main/java/seedu/fridgefriend/utilities/Storage.java]: remove

**Review by kwokyto — APPROVED** [review]
LGTM
