### PR TITLE
Refine Add and List commands to new quantity feature

### LINKED ISSUE #109: As a user, if I add a food that is already in the frdge before, the quantity will pile up.
Check if foodname is already used in previous foods. 
-If not, add new food. 
-If so, check if storage location, expiry are the same. 
    ~If all same, then quantity adds up. 
    ~If not, throw an exception and request user to use a new foodname.

### PR DESCRIPTION
**Pull request by Vinci-Hu**

### CODE REVIEW

**Review by SimJJ96 — APPROVED** [review]
LGTM

File: src/test/java/seedu/fridgefriend/command/AddCommandTest.java [hunk 1]
```diff
@@ -81,4 +82,25 @@ public void addCommand_invalidDate_InvalidDateException() {
...
+        AddCommand addCommand2 = new AddCommand("Milk", FoodCategory.DAIRY,
+                "31-12-2021", FoodStorageLocation.FRIDGE_DOOR, 3);
+        addCommand2.setData(fridge);
+        addCommand2.execute();
+        assertEquals(1, fridge.getSize());
+        assertEquals(5, fridge.getFood(0).getQuantity());
+
+        String expectedMessage = "Great! I have added Milk into your fridge.\n"
+                + "Details: Food name: Milk, category: DAIRY, "
+                + "expiry: 31-12-2021, stored in: FRIDGE_DOOR, quantity: 3";
```
Comment (SimJJ96) [inline src/test/java/seedu/fridgefriend/command/AddCommandTest.java:101]: Should the message here be quantity 5?

Comment (Vinci-Hu) [reply src/test/java/seedu/fridgefriend/command/AddCommandTest.java:101]: Will solve this in next pr!

File: src/main/java/seedu/fridgefriend/food/Fridge.java [hunk 2]
```diff
@@ -1,12 +1,33 @@
...
+    /**
+     * Call the UniqueFoodnameChecker methods before adding.
+     * Checks if foodname already exists;
+     * checks if its quantity can be added to existing food item.
+     * If foodname exists but storage or expiry information are not identical,
+     * will throw an exception to ask user to use a different foodname.
+     * @param food food object to add obtained from parser.
+     * @throws RepetitiveFoodIdentifierException as name suggests.
+     */
+    public void add(Food food) throws RepetitiveFoodIdentifierException {
```
Comment (kwokyto) [inline src/main/java/seedu/fridgefriend/food/Fridge.java:19]: i think can push this into a if-elseif  instead of a nested if-else

File: src/main/java/seedu/fridgefriend/food/UniqueFoodnameChecker.java [hunk 3]
```diff
@@ -0,0 +1,39 @@
+package seedu.fridgefriend.food;
```
Comment (kwokyto) [inline src/main/java/seedu/fridgefriend/food/UniqueFoodnameChecker.java:1]: shall we shift this to utilities?

**Review by kwokyto — APPROVED** [review]
Other than those stated in comments, LGTM
